/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.api;

import io.swagger.eveportal.client.ApiException;
import io.swagger.eveportal.client.model.CtxBlueprintInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ContextBlueprintCatalogueApiApi
 */
@Ignore
public class ContextBlueprintCatalogueApiApiTest {

    private final ContextBlueprintCatalogueApiApi api = new ContextBlueprintCatalogueApiApi();

    
    /**
     * Get ALL CtxBlueprints
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllCtxBlueprintsUsingGETTest() throws ApiException {
        Boolean authenticated = null;
        String authorities0Authority = null;
        List<CtxBlueprintInfo> response = api.getAllCtxBlueprintsUsingGET(authenticated, authorities0Authority);

        // TODO: test validations
    }
    
    /**
     * Get CtxBlueprint
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCtxBlueprintUsingGETTest() throws ApiException {
        String ctxbId = null;
        Boolean authenticated = null;
        String authorities0Authority = null;
        CtxBlueprintInfo response = api.getCtxBlueprintUsingGET(ctxbId, authenticated, authorities0Authority);

        // TODO: test validations
    }
    
}
