/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.api;

import io.swagger.eveportal.client.ApiException;
import io.swagger.eveportal.client.model.ExpBlueprintInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for ExperimentBlueprintCatalogueApiApi
 */
@Ignore
public class ExperimentBlueprintCatalogueApiApiTest {

    private final ExperimentBlueprintCatalogueApiApi api = new ExperimentBlueprintCatalogueApiApi();

    
    /**
     * Get ALL ExpBlueprints
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllExpBlueprintsUsingGETTest() throws ApiException {
        Boolean authenticated = null;
        String authorities0Authority = null;
        String id = null;
        String vsbId = null;
        List<String> response = api.getAllExpBlueprintsUsingGET(authenticated, authorities0Authority, id, vsbId);

        // TODO: test validations
    }
    
    /**
     * Get ExpBlueprint
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getExpBlueprintUsingGETTest() throws ApiException {
        String expbId = null;
        Boolean authenticated = null;
        String authorities0Authority = null;
        ExpBlueprintInfo response = api.getExpBlueprintUsingGET(expbId, authenticated, authorities0Authority);

        // TODO: test validations
    }
    
}
