/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.api;

import io.swagger.eveportal.client.ApiException;
import io.swagger.eveportal.client.model.TestCaseDescriptor;
import org.junit.Test;
import org.junit.Ignore;

import java.util.List;

/**
 * API tests for TestCaseDescriptorCatalogueApiApi
 */
@Ignore
public class TestCaseDescriptorCatalogueApiApiTest {

    private final TestCaseDescriptorCatalogueApiApi api = new TestCaseDescriptorCatalogueApiApi();

    
    /**
     * Query ALL the Test Case Descriptors
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllTestCaseDescriptorsUsingGETTest() throws ApiException {
        Boolean authenticated = null;
        String authorities0Authority = null;
        List<TestCaseDescriptor> response = api.getAllTestCaseDescriptorsUsingGET(authenticated, authorities0Authority);

        // TODO: test validations
    }
    
    /**
     * Query a Test Case Descriptor with a given ID
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTcDescriptorUsingGETTest() throws ApiException {
        String tcdId = null;
        Boolean authenticated = null;
        String authorities0Authority = null;
        TestCaseDescriptor response = api.getTcDescriptorUsingGET(tcdId, authenticated, authorities0Authority);

        // TODO: test validations
    }
    
}
