/*
 * 5G-EVE RBAC module
 * RBAC module for 5G-EVE portal
 *
 * OpenAPI spec version: 0.0.1
 * Contact: gigarcia@it.uc3m.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.rbac.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
