/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * VsbEndpoint
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class VsbEndpoint {
  @SerializedName("endPointId")
  private String endPointId = null;

  @SerializedName("external")
  private Boolean external = null;

  @SerializedName("management")
  private Boolean management = null;

  @SerializedName("ranConnection")
  private Boolean ranConnection = null;

  public VsbEndpoint endPointId(String endPointId) {
    this.endPointId = endPointId;
    return this;
  }

   /**
   * Get endPointId
   * @return endPointId
  **/
  @ApiModelProperty(value = "")
  public String getEndPointId() {
    return endPointId;
  }

  public void setEndPointId(String endPointId) {
    this.endPointId = endPointId;
  }

  public VsbEndpoint external(Boolean external) {
    this.external = external;
    return this;
  }

   /**
   * Get external
   * @return external
  **/
  @ApiModelProperty(value = "")
  public Boolean isExternal() {
    return external;
  }

  public void setExternal(Boolean external) {
    this.external = external;
  }

  public VsbEndpoint management(Boolean management) {
    this.management = management;
    return this;
  }

   /**
   * Get management
   * @return management
  **/
  @ApiModelProperty(value = "")
  public Boolean isManagement() {
    return management;
  }

  public void setManagement(Boolean management) {
    this.management = management;
  }

  public VsbEndpoint ranConnection(Boolean ranConnection) {
    this.ranConnection = ranConnection;
    return this;
  }

   /**
   * Get ranConnection
   * @return ranConnection
  **/
  @ApiModelProperty(value = "")
  public Boolean isRanConnection() {
    return ranConnection;
  }

  public void setRanConnection(Boolean ranConnection) {
    this.ranConnection = ranConnection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VsbEndpoint vsbEndpoint = (VsbEndpoint) o;
    return Objects.equals(this.endPointId, vsbEndpoint.endPointId) &&
        Objects.equals(this.external, vsbEndpoint.external) &&
        Objects.equals(this.management, vsbEndpoint.management) &&
        Objects.equals(this.ranConnection, vsbEndpoint.ranConnection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endPointId, external, management, ranConnection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VsbEndpoint {\n");
    
    sb.append("    endPointId: ").append(toIndentedString(endPointId)).append("\n");
    sb.append("    external: ").append(toIndentedString(external)).append("\n");
    sb.append("    management: ").append(toIndentedString(management)).append("\n");
    sb.append("    ranConnection: ").append(toIndentedString(ranConnection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

