/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * GetRadioChunkTopo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class GetRadioChunkTopo {

  @JsonProperty("selectedLinks")
  private List<Object> selectedLinks = null;
  
  @JsonProperty("selectedPhys")
  private List<Object> selectedPhys = null;
  
  public GetRadioChunkTopo selectedLinks(List<Object> selectedLinks) {
    this.selectedLinks = selectedLinks;
    return this;
  }

  public GetRadioChunkTopo addSelectedLinksItem(Object selectedLinksItem) {
    
    if (this.selectedLinks == null) {
      this.selectedLinks = new ArrayList<Object>();
    }
    
    this.selectedLinks.add(selectedLinksItem);
    return this;
  }
  
  /**
  * Get selectedLinks
  * @return selectedLinks
  **/
  @ApiModelProperty(value = "")
  public List<Object> getSelectedLinks() {
    return selectedLinks;
  }
  public void setSelectedLinks(List<Object> selectedLinks) {
    this.selectedLinks = selectedLinks;
  }
  
  public GetRadioChunkTopo selectedPhys(List<Object> selectedPhys) {
    this.selectedPhys = selectedPhys;
    return this;
  }

  public GetRadioChunkTopo addSelectedPhysItem(Object selectedPhysItem) {
    
    if (this.selectedPhys == null) {
      this.selectedPhys = new ArrayList<Object>();
    }
    
    this.selectedPhys.add(selectedPhysItem);
    return this;
  }
  
  /**
  * Get selectedPhys
  * @return selectedPhys
  **/
  @ApiModelProperty(value = "")
  public List<Object> getSelectedPhys() {
    return selectedPhys;
  }
  public void setSelectedPhys(List<Object> selectedPhys) {
    this.selectedPhys = selectedPhys;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetRadioChunkTopo getRadioChunkTopo = (GetRadioChunkTopo) o;
    return Objects.equals(this.selectedLinks, getRadioChunkTopo.selectedLinks) &&
        Objects.equals(this.selectedPhys, getRadioChunkTopo.selectedPhys);
  }

  @Override
  public int hashCode() {
    return Objects.hash(selectedLinks, selectedPhys);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetRadioChunkTopo {\n");
    
    sb.append("    selectedLinks: ").append(toIndentedString(selectedLinks)).append("\n");
    sb.append("    selectedPhys: ").append(toIndentedString(selectedPhys)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



