/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PostNetworkChunk
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class PostNetworkChunk {

  @JsonProperty("name")
  private String name = null;
  
  @JsonProperty("id")
  private String id = null;
  
  @JsonProperty("user_id")
  private String userId = null;
  
  @JsonProperty("physical_network_id")
  private String physicalNetworkId = null;
  
  @JsonProperty("compute_chunk_id")
  private String computeChunkId = null;
  
  @JsonProperty("tag")
  private Integer tag = null;
  
  @JsonProperty("cidr")
  private String cidr = null;
  
  @JsonProperty("os_netowrk_id")
  private String osNetowrkId = null;
  
  @JsonProperty("requirements")
  private Object requirements = null;
  
  @JsonProperty("role")
  private String role = null;
  
  public PostNetworkChunk name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Get name
  * @return name
  **/
  @ApiModelProperty(example = "network_chunk2", value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public PostNetworkChunk id(String id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  
  public PostNetworkChunk userId(String userId) {
    this.userId = userId;
    return this;
  }

  
  /**
  * Get userId
  * @return userId
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }
  
  public PostNetworkChunk physicalNetworkId(String physicalNetworkId) {
    this.physicalNetworkId = physicalNetworkId;
    return this;
  }

  
  /**
  * Get physicalNetworkId
  * @return physicalNetworkId
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getPhysicalNetworkId() {
    return physicalNetworkId;
  }
  public void setPhysicalNetworkId(String physicalNetworkId) {
    this.physicalNetworkId = physicalNetworkId;
  }
  
  public PostNetworkChunk computeChunkId(String computeChunkId) {
    this.computeChunkId = computeChunkId;
    return this;
  }

  
  /**
  * Get computeChunkId
  * @return computeChunkId
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getComputeChunkId() {
    return computeChunkId;
  }
  public void setComputeChunkId(String computeChunkId) {
    this.computeChunkId = computeChunkId;
  }
  
  public PostNetworkChunk tag(Integer tag) {
    this.tag = tag;
    return this;
  }

  
  /**
  * Get tag
  * @return tag
  **/
  @ApiModelProperty(example = "103", value = "")
  public Integer getTag() {
    return tag;
  }
  public void setTag(Integer tag) {
    this.tag = tag;
  }
  
  public PostNetworkChunk cidr(String cidr) {
    this.cidr = cidr;
    return this;
  }

  
  /**
  * Get cidr
  * @return cidr
  **/
  @ApiModelProperty(example = "192.168.101.0/24", value = "")
  public String getCidr() {
    return cidr;
  }
  public void setCidr(String cidr) {
    this.cidr = cidr;
  }
  
  public PostNetworkChunk osNetowrkId(String osNetowrkId) {
    this.osNetowrkId = osNetowrkId;
    return this;
  }

  
  /**
  * Get osNetowrkId
  * @return osNetowrkId
  **/
  @ApiModelProperty(example = "92b60b94-a554-46d8-9521-f7212b913daf", value = "")
  public String getOsNetowrkId() {
    return osNetowrkId;
  }
  public void setOsNetowrkId(String osNetowrkId) {
    this.osNetowrkId = osNetowrkId;
  }
  
  public PostNetworkChunk requirements(Object requirements) {
    this.requirements = requirements;
    return this;
  }

  
  /**
  * Get requirements
  * @return requirements
  **/
  @ApiModelProperty(value = "")
  public Object getRequirements() {
    return requirements;
  }
  public void setRequirements(Object requirements) {
    this.requirements = requirements;
  }
  
  public PostNetworkChunk role(String role) {
    this.role = role;
    return this;
  }

  
  /**
  * Get role
  * @return role
  **/
  @ApiModelProperty(example = "data-network", value = "")
  public String getRole() {
    return role;
  }
  public void setRole(String role) {
    this.role = role;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostNetworkChunk postNetworkChunk = (PostNetworkChunk) o;
    return Objects.equals(this.name, postNetworkChunk.name) &&
        Objects.equals(this.id, postNetworkChunk.id) &&
        Objects.equals(this.userId, postNetworkChunk.userId) &&
        Objects.equals(this.physicalNetworkId, postNetworkChunk.physicalNetworkId) &&
        Objects.equals(this.computeChunkId, postNetworkChunk.computeChunkId) &&
        Objects.equals(this.tag, postNetworkChunk.tag) &&
        Objects.equals(this.cidr, postNetworkChunk.cidr) &&
        Objects.equals(this.osNetowrkId, postNetworkChunk.osNetowrkId) &&
        Objects.equals(this.requirements, postNetworkChunk.requirements) &&
        Objects.equals(this.role, postNetworkChunk.role);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, userId, physicalNetworkId, computeChunkId, tag, cidr, osNetowrkId, requirements, role);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostNetworkChunk {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    physicalNetworkId: ").append(toIndentedString(physicalNetworkId)).append("\n");
    sb.append("    computeChunkId: ").append(toIndentedString(computeChunkId)).append("\n");
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    cidr: ").append(toIndentedString(cidr)).append("\n");
    sb.append("    osNetowrkId: ").append(toIndentedString(osNetowrkId)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



