/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PostComputeChunk
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class PostComputeChunk {

  @JsonProperty("name")
  private String name = null;
  
  @JsonProperty("id")
  private String id = null;
  
  @JsonProperty("user_id")
  private String userId = null;
  
  @JsonProperty("username")
  private String username = null;
  
  @JsonProperty("description")
  private String description = null;
  
  @JsonProperty("compute_id")
  private String computeId = null;
  
  @JsonProperty("availability_zone")
  private String availabilityZone = null;
  
  @JsonProperty("requirements")
  private Object requirements = null;
  
  @JsonProperty("available_ext_net")
  private Boolean availableExtNet = null;
  
  public PostComputeChunk name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Get name
  * @return name
  **/
  @ApiModelProperty(example = "compute_chunk", value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public PostComputeChunk id(String id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  
  public PostComputeChunk userId(String userId) {
    this.userId = userId;
    return this;
  }

  
  /**
  * Get userId
  * @return userId
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }
  
  public PostComputeChunk username(String username) {
    this.username = username;
    return this;
  }

  
  /**
  * Get username
  * @return username
  **/
  @ApiModelProperty(example = "username", value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }
  
  public PostComputeChunk description(String description) {
    this.description = description;
    return this;
  }

  
  /**
  * Get description
  * @return description
  **/
  @ApiModelProperty(example = "Compute node 1 on test-bed 2", value = "")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  
  public PostComputeChunk computeId(String computeId) {
    this.computeId = computeId;
    return this;
  }

  
  /**
  * Get computeId
  * @return computeId
  **/
  @ApiModelProperty(example = "5b63089158f568073093f70d", value = "")
  public String getComputeId() {
    return computeId;
  }
  public void setComputeId(String computeId) {
    this.computeId = computeId;
  }
  
  public PostComputeChunk availabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
    return this;
  }

  
  /**
  * Get availabilityZone
  * @return availabilityZone
  **/
  @ApiModelProperty(example = "nova", value = "")
  public String getAvailabilityZone() {
    return availabilityZone;
  }
  public void setAvailabilityZone(String availabilityZone) {
    this.availabilityZone = availabilityZone;
  }
  
  public PostComputeChunk requirements(Object requirements) {
    this.requirements = requirements;
    return this;
  }

  
  /**
  * Get requirements
  * @return requirements
  **/
  @ApiModelProperty(value = "")
  public Object getRequirements() {
    return requirements;
  }
  public void setRequirements(Object requirements) {
    this.requirements = requirements;
  }
  
  public PostComputeChunk availableExtNet(Boolean availableExtNet) {
    this.availableExtNet = availableExtNet;
    return this;
  }

  
  /**
  * Get availableExtNet
  * @return availableExtNet
  **/
  @ApiModelProperty(example = "false", value = "")
  public Boolean isAvailableExtNet() {
    return availableExtNet;
  }
  public void setAvailableExtNet(Boolean availableExtNet) {
    this.availableExtNet = availableExtNet;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PostComputeChunk postComputeChunk = (PostComputeChunk) o;
    return Objects.equals(this.name, postComputeChunk.name) &&
        Objects.equals(this.id, postComputeChunk.id) &&
        Objects.equals(this.userId, postComputeChunk.userId) &&
        Objects.equals(this.username, postComputeChunk.username) &&
        Objects.equals(this.description, postComputeChunk.description) &&
        Objects.equals(this.computeId, postComputeChunk.computeId) &&
        Objects.equals(this.availabilityZone, postComputeChunk.availabilityZone) &&
        Objects.equals(this.requirements, postComputeChunk.requirements) &&
        Objects.equals(this.availableExtNet, postComputeChunk.availableExtNet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, userId, username, description, computeId, availabilityZone, requirements, availableExtNet);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostComputeChunk {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    computeId: ").append(toIndentedString(computeId)).append("\n");
    sb.append("    availabilityZone: ").append(toIndentedString(availabilityZone)).append("\n");
    sb.append("    requirements: ").append(toIndentedString(requirements)).append("\n");
    sb.append("    availableExtNet: ").append(toIndentedString(availableExtNet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



