/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PutLTEConfigurationInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class PutLTEConfigurationInput {

  @JsonProperty("earfcnDL")
  private Integer earfcnDL = null;
  
  @JsonProperty("refSignalPower")
  private Integer refSignalPower = null;
  
  @JsonProperty("phyCellId")
  private Integer phyCellId = null;
  
  public PutLTEConfigurationInput earfcnDL(Integer earfcnDL) {
    this.earfcnDL = earfcnDL;
    return this;
  }

  
  /**
  * Get earfcnDL
  * @return earfcnDL
  **/
  @ApiModelProperty(example = "41690", value = "")
  public Integer getEarfcnDL() {
    return earfcnDL;
  }
  public void setEarfcnDL(Integer earfcnDL) {
    this.earfcnDL = earfcnDL;
  }
  
  public PutLTEConfigurationInput refSignalPower(Integer refSignalPower) {
    this.refSignalPower = refSignalPower;
    return this;
  }

  
  /**
  * Get refSignalPower
  * @return refSignalPower
  **/
  @ApiModelProperty(example = "-40", value = "")
  public Integer getRefSignalPower() {
    return refSignalPower;
  }
  public void setRefSignalPower(Integer refSignalPower) {
    this.refSignalPower = refSignalPower;
  }
  
  public PutLTEConfigurationInput phyCellId(Integer phyCellId) {
    this.phyCellId = phyCellId;
    return this;
  }

  
  /**
  * Get phyCellId
  * @return phyCellId
  **/
  @ApiModelProperty(example = "512", value = "")
  public Integer getPhyCellId() {
    return phyCellId;
  }
  public void setPhyCellId(Integer phyCellId) {
    this.phyCellId = phyCellId;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutLTEConfigurationInput putLTEConfigurationInput = (PutLTEConfigurationInput) o;
    return Objects.equals(this.earfcnDL, putLTEConfigurationInput.earfcnDL) &&
        Objects.equals(this.refSignalPower, putLTEConfigurationInput.refSignalPower) &&
        Objects.equals(this.phyCellId, putLTEConfigurationInput.phyCellId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(earfcnDL, refSignalPower, phyCellId);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutLTEConfigurationInput {\n");
    
    sb.append("    earfcnDL: ").append(toIndentedString(earfcnDL)).append("\n");
    sb.append("    refSignalPower: ").append(toIndentedString(refSignalPower)).append("\n");
    sb.append("    phyCellId: ").append(toIndentedString(phyCellId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



