/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * PutRFPortConfigInput
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class PutRFPortConfigInput {

  @JsonProperty("band")
  private Integer band = null;
  
  public PutRFPortConfigInput band(Integer band) {
    this.band = band;
    return this;
  }

  
  /**
  * Get band
  * @return band
  **/
  @ApiModelProperty(example = "78", value = "")
  public Integer getBand() {
    return band;
  }
  public void setBand(Integer band) {
    this.band = band;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PutRFPortConfigInput putRFPortConfigInput = (PutRFPortConfigInput) o;
    return Objects.equals(this.band, putRFPortConfigInput.band);
  }

  @Override
  public int hashCode() {
    return Objects.hash(band);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PutRFPortConfigInput {\n");
    
    sb.append("    band: ").append(toIndentedString(band)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



