/*
 * Slice Manager API
 * This API provides interaction between the N-NaaS platform and the Slice Manager.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.slice_manager.v2.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Slic3Put
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2022-05-17T10:16:59.588+02:00")
public class Slic3Put {

  @JsonProperty("chunk_ids")
  private List<String> chunkIds = null;
  
  public Slic3Put chunkIds(List<String> chunkIds) {
    this.chunkIds = chunkIds;
    return this;
  }

  public Slic3Put addChunkIdsItem(String chunkIdsItem) {
    
    if (this.chunkIds == null) {
      this.chunkIds = new ArrayList<String>();
    }
    
    this.chunkIds.add(chunkIdsItem);
    return this;
  }
  
  /**
  * Get chunkIds
  * @return chunkIds
  **/
  @ApiModelProperty(value = "")
  public List<String> getChunkIds() {
    return chunkIds;
  }
  public void setChunkIds(List<String> chunkIds) {
    this.chunkIds = chunkIds;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Slic3Put slic3Put = (Slic3Put) o;
    return Objects.equals(this.chunkIds, slic3Put.chunkIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(chunkIds);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Slic3Put {\n");
    
    sb.append("    chunkIds: ").append(toIndentedString(chunkIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



