#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '3.5'


services:


  nssmf_core_ingenious_final_review:
     container_name: nssmf_core_ingenious_final_review
     image: nssmf-core-ingenious:0.0.1-final-review
     restart: always
     ports:
       - '8899:8081'
     command: >
       bash -c "/usr/bin/java -jar /home/ubuntu/nssmf-app-0.0.1.jar"
     environment:
       - server.port=8081
       - spring.datasource.url=jdbc:postgresql://postgres:5432/nssmf_core_final_review
       - spring.datasource.username=postgres
       - spring.datasource.password=postgres
       - security.basic.enabled=false
       - sebastian.admin=admin
       - management.security.enabled=false
       - nssmf.eventhandler.class=it.nextworks.nfvmano.nssmf.core.nssmanagement.CoreLcmEventHandler
       - nssmf.provisioning.message.class=it.nextworks.nfvmano.libs.vs.common.nssmf.messages.specialized.core.cumucore.CoreSlicePayload
       - nssmf.provisionig.baseurl=/core/nssmf/provisioning
       - nssmf.provisioning.baseurl=/core/nssmf/provisioning
       - nssmf.nsmfnotifier.loginUrl=noLogin
       - nssmf.nsmfnotifier.notifyUrl=http://nsmf_ingenious:8080/vs/basic/nslcm/nss/%nssi_id%/notify
       - nssmf.nsmfnotifier.url=http://nsmf_ingenious:8080/vs/basic/nslcm/nss/%nssi_id%/notify
       - nssmf.osm.baseurl=http://10.30.8.214/osm
       - nssmf.osm.username=admin
       - nssmf.osm.password=admin
       - nssmf.osm.project=admin
       - nssmf.osm.vim-id=43be7258-61f5-4820-ae12-f3de16cdb2c0
       - nfvo.lcm.polling=10
       - nssmf.cnc.port=3000
       - nssmf.vim.ext-cp-core=cp_5Gcore-ext
       - nssmf.vim.ext-mgmt-core=cp_mgmt-ext
       - nssmf.cnc.ip=10.30.8.246
       - nssmf.skipNsdDeployment=false
       - nssmf.coreInstanceId=abcd91b9-6c9e-470c-90f9-f78584b6abcd
     #depends_on:
     #  - postgres
     networks:
        vertical-slicer:
         ipv4_address: 10.5.0.10

  postgres:
    container_name: postgres
    image: ghcr.io/nextworks-it/network-slice-management-function/multiple-postgres-db
    #image: postgres:latest
    restart: always
    environment:
      POSTGRES_MULTIPLE_DATABASES: nsmf, nssmf_core_final_review
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - 0.0.0.0:5432:5432
    networks:
        vertical-slicer:
         ipv4_address: 10.5.0.6

  rabbit:
     container_name: rabbit
     image: rabbitmq
     ports:
       - 5672:5672
       - 15672:15672
     networks:
        vertical-slicer:
         ipv4_address: 10.5.0.5


networks:
  vertical-slicer:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
