#check java
- name: Fetch Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- debug:
    msg: "JRE is present, but in a version different than 8. Only JRE 8 is officially supported. Please install Java 8 manually and configure it."
  when: '"1.8" not in java_version.stdout and java_version.stdout != ""'

- meta: end_play
  when: '"1.8" not in java_version.stdout and java_version.stdout != ""'

- name: Installing java 8
  apt:
    name: openjdk-8-jdk
    state: present
  become: yes

- name: Update packages
  apt:
    update_cache: yes
  become: yes

#check maven
- name: "Check if maven is installed"
  package_facts:
    manager: "auto"

- name: Installing maven
  apt:
    name: maven
  when: "'maven' not in ansible_facts.packages"
  become: yes

#check rabbitmq
- name: "Check if rabbit is installed"
  apt:
    name: rabbitmq-server
  become: yes
  when: "'rabbitmq-server' not in ansible_facts.packages"

#check postgresdb
- name: "Check if postgres is installed"
  apt:
    name: postgresql
  become: yes
  when: "'postgresql' not in ansible_facts.packages"
  
- debug:
    msg: "Trying to create slicer folder at {{ slicer_folder }}"

- name: check if working dir already exist
  stat:
    path: "{{ slicer_folder }}"
  register: check_output

- debug:
    msg: "The directory already exists. Skipping clone of the repo."
  when: check_output.stat.exists 

- name: create slicer directory
  file:
    path: "{{ slicer_folder }}"
    state: directory
  when: not check_output.stat.exists
  
#get repos    
- name: get nfv-ifa-libs
  shell: cd {{ slicer_folder }} && git clone --branch {{ ifa_libs_branch }} {{ ifa_libs_path }}
  when: not check_output.stat.exists

- name: get identity-mangement
  shell: cd {{ slicer_folder }} && git clone {{ identity_mangement_path }} slicer-identity-mgmt
  when: not check_output.stat.exists

- name: get blueprint-catalogue
  shell: cd {{ slicer_folder }} && git clone --branch {{ blueprint_catalogue_branch }} {{ blueprint_catalogue_path }}
  when: not check_output.stat.exists

- name: get nfv-sol-libs
  shell: cd {{ slicer_folder }} && git clone {{ sol_libs_path }}
  when: not check_output.stat.exists

#5g repo and timeo repo
- name: get 5g-catalogue repo
  shell: cd {{ slicer_folder }} && git clone {{ fiveg_catalogue_path }}
  when: not check_output.stat.exists

- name: get config manager client repo
  shell: cd {{ slicer_folder }} && git clone {{ config_manager_client_path }}
  when: not check_output.stat.exists

- name: get nfvo-driver
  shell: cd {{ slicer_folder }} && git clone --branch {{ nfvo_driver_branch }} {{ nfvo_driver_path }}
  when: not check_output.stat.exists

- name: get slicer
  shell: cd {{ slicer_folder }} && git clone --branch {{ slicer_branch }} {{ slicer_path }} slicer
  when: not check_output.stat.exists
