- name: compiling nfv-ifa-libs
  shell: cd {{ slicer_folder }}/nfv-ifa-libs && mvn clean install

- name: compiling identity-management
  shell: cd {{ slicer_folder }}/slicer-identity-mgmt && mvn clean install

- name: compiling nfv-sol-libs
  shell: cd {{ slicer_folder }}/nfv-sol-libs && ./install_nfv_sol_libs.sh

############ to be changed ###########
- name: compiling OSMr4PlusClient
  shell: cd {{ slicer_folder }}/5g-catalogue/OSMr4PlusDataModel && mvn clean install

- name: compiling ConfigManagerClient
  shell: cd {{ slicer_folder }}/config-manager-client/ConfigManagerClient && mvn clean install

- name: compiling nfvo-driver
  shell: cd {{ slicer_folder }}/nfvo-drivers && mvn clean install
#######################################

- name: compiling slicer-catalogue
  shell: cd {{ slicer_folder }}/slicer-catalogue && mvn clean install

- name: compiling 5geve rest client
  shell: cd {{ slicer_folder }}/slicer/5GEVE_REST_CLIENTS && mvn clean install

- name: compiling record service im
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/RecordServiceIM && mvn clean install

- name: compiling record services
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/RecordService && mvn clean install

- name: compiling common_element
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/CommonElements && mvn clean install

- name: compiling arbitrator interfaces
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/ARBITRATOR_INTERFACES && mvn clean install

- name: compiling nsfm interfaces
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/NSFM_INTERFACES && mvn clean install

- name: compiling arbitrator service
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/ARBITRATOR_SERVICE && mvn clean install

- name: compiling vsmf_interfaces
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/VSFM_INTERFACES && mvn clean install

- name: compiling vsmf_services
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/VSFM_SERVICE && mvn clean install

- name: compiling nsfm service
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/NSFM_SERVICE && mvn clean install

- name: compiling nsfm service
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/NFVO_CATALOGUE_REST && mvn clean install

- name: compiling sebastian core
  shell: cd {{ slicer_folder }}/slicer/SEBASTIAN/SEBASTIAN_CORE && mvn clean install
