/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * CtxBlueprintInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class CtxBlueprintInfo {
  @SerializedName("activeCtxdId")
  private List<String> activeCtxdId = null;

  @SerializedName("ctxBlueprint")
  private CtxBlueprint ctxBlueprint = null;

  @SerializedName("ctxBlueprintId")
  private String ctxBlueprintId = null;

  @SerializedName("ctxBlueprintVersion")
  private String ctxBlueprintVersion = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("onBoardedNsdInfoId")
  private List<String> onBoardedNsdInfoId = null;

  @SerializedName("owner")
  private String owner = null;

  public CtxBlueprintInfo activeCtxdId(List<String> activeCtxdId) {
    this.activeCtxdId = activeCtxdId;
    return this;
  }

  public CtxBlueprintInfo addActiveCtxdIdItem(String activeCtxdIdItem) {
    if (this.activeCtxdId == null) {
      this.activeCtxdId = new ArrayList<String>();
    }
    this.activeCtxdId.add(activeCtxdIdItem);
    return this;
  }

   /**
   * Get activeCtxdId
   * @return activeCtxdId
  **/
  @ApiModelProperty(value = "")
  public List<String> getActiveCtxdId() {
    return activeCtxdId;
  }

  public void setActiveCtxdId(List<String> activeCtxdId) {
    this.activeCtxdId = activeCtxdId;
  }

  public CtxBlueprintInfo ctxBlueprint(CtxBlueprint ctxBlueprint) {
    this.ctxBlueprint = ctxBlueprint;
    return this;
  }

   /**
   * Get ctxBlueprint
   * @return ctxBlueprint
  **/
  @ApiModelProperty(value = "")
  public CtxBlueprint getCtxBlueprint() {
    return ctxBlueprint;
  }

  public void setCtxBlueprint(CtxBlueprint ctxBlueprint) {
    this.ctxBlueprint = ctxBlueprint;
  }

  public CtxBlueprintInfo ctxBlueprintId(String ctxBlueprintId) {
    this.ctxBlueprintId = ctxBlueprintId;
    return this;
  }

   /**
   * Get ctxBlueprintId
   * @return ctxBlueprintId
  **/
  @ApiModelProperty(value = "")
  public String getCtxBlueprintId() {
    return ctxBlueprintId;
  }

  public void setCtxBlueprintId(String ctxBlueprintId) {
    this.ctxBlueprintId = ctxBlueprintId;
  }

  public CtxBlueprintInfo ctxBlueprintVersion(String ctxBlueprintVersion) {
    this.ctxBlueprintVersion = ctxBlueprintVersion;
    return this;
  }

   /**
   * Get ctxBlueprintVersion
   * @return ctxBlueprintVersion
  **/
  @ApiModelProperty(value = "")
  public String getCtxBlueprintVersion() {
    return ctxBlueprintVersion;
  }

  public void setCtxBlueprintVersion(String ctxBlueprintVersion) {
    this.ctxBlueprintVersion = ctxBlueprintVersion;
  }

  public CtxBlueprintInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CtxBlueprintInfo onBoardedNsdInfoId(List<String> onBoardedNsdInfoId) {
    this.onBoardedNsdInfoId = onBoardedNsdInfoId;
    return this;
  }

  public CtxBlueprintInfo addOnBoardedNsdInfoIdItem(String onBoardedNsdInfoIdItem) {
    if (this.onBoardedNsdInfoId == null) {
      this.onBoardedNsdInfoId = new ArrayList<String>();
    }
    this.onBoardedNsdInfoId.add(onBoardedNsdInfoIdItem);
    return this;
  }

   /**
   * Get onBoardedNsdInfoId
   * @return onBoardedNsdInfoId
  **/
  @ApiModelProperty(value = "")
  public List<String> getOnBoardedNsdInfoId() {
    return onBoardedNsdInfoId;
  }

  public void setOnBoardedNsdInfoId(List<String> onBoardedNsdInfoId) {
    this.onBoardedNsdInfoId = onBoardedNsdInfoId;
  }

  public CtxBlueprintInfo owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @ApiModelProperty(value = "")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CtxBlueprintInfo ctxBlueprintInfo = (CtxBlueprintInfo) o;
    return Objects.equals(this.activeCtxdId, ctxBlueprintInfo.activeCtxdId) &&
        Objects.equals(this.ctxBlueprint, ctxBlueprintInfo.ctxBlueprint) &&
        Objects.equals(this.ctxBlueprintId, ctxBlueprintInfo.ctxBlueprintId) &&
        Objects.equals(this.ctxBlueprintVersion, ctxBlueprintInfo.ctxBlueprintVersion) &&
        Objects.equals(this.name, ctxBlueprintInfo.name) &&
        Objects.equals(this.onBoardedNsdInfoId, ctxBlueprintInfo.onBoardedNsdInfoId) &&
        Objects.equals(this.owner, ctxBlueprintInfo.owner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeCtxdId, ctxBlueprint, ctxBlueprintId, ctxBlueprintVersion, name, onBoardedNsdInfoId, owner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CtxBlueprintInfo {\n");
    
    sb.append("    activeCtxdId: ").append(toIndentedString(activeCtxdId)).append("\n");
    sb.append("    ctxBlueprint: ").append(toIndentedString(ctxBlueprint)).append("\n");
    sb.append("    ctxBlueprintId: ").append(toIndentedString(ctxBlueprintId)).append("\n");
    sb.append("    ctxBlueprintVersion: ").append(toIndentedString(ctxBlueprintVersion)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    onBoardedNsdInfoId: ").append(toIndentedString(onBoardedNsdInfoId)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

