/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * ExpBlueprintInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class ExpBlueprintInfo {
  @SerializedName("activeExpdId")
  private List<String> activeExpdId = null;

  @SerializedName("expBlueprint")
  private ExpBlueprint expBlueprint = null;

  @SerializedName("expBlueprintId")
  private String expBlueprintId = null;

  @SerializedName("expBlueprintVersion")
  private String expBlueprintVersion = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("onBoardedNsdInfoId")
  private List<String> onBoardedNsdInfoId = null;

  public ExpBlueprintInfo activeExpdId(List<String> activeExpdId) {
    this.activeExpdId = activeExpdId;
    return this;
  }

  public ExpBlueprintInfo addActiveExpdIdItem(String activeExpdIdItem) {
    if (this.activeExpdId == null) {
      this.activeExpdId = new ArrayList<String>();
    }
    this.activeExpdId.add(activeExpdIdItem);
    return this;
  }

   /**
   * Get activeExpdId
   * @return activeExpdId
  **/
  @ApiModelProperty(value = "")
  public List<String> getActiveExpdId() {
    return activeExpdId;
  }

  public void setActiveExpdId(List<String> activeExpdId) {
    this.activeExpdId = activeExpdId;
  }

  public ExpBlueprintInfo expBlueprint(ExpBlueprint expBlueprint) {
    this.expBlueprint = expBlueprint;
    return this;
  }

   /**
   * Get expBlueprint
   * @return expBlueprint
  **/
  @ApiModelProperty(value = "")
  public ExpBlueprint getExpBlueprint() {
    return expBlueprint;
  }

  public void setExpBlueprint(ExpBlueprint expBlueprint) {
    this.expBlueprint = expBlueprint;
  }

  public ExpBlueprintInfo expBlueprintId(String expBlueprintId) {
    this.expBlueprintId = expBlueprintId;
    return this;
  }

   /**
   * Get expBlueprintId
   * @return expBlueprintId
  **/
  @ApiModelProperty(value = "")
  public String getExpBlueprintId() {
    return expBlueprintId;
  }

  public void setExpBlueprintId(String expBlueprintId) {
    this.expBlueprintId = expBlueprintId;
  }

  public ExpBlueprintInfo expBlueprintVersion(String expBlueprintVersion) {
    this.expBlueprintVersion = expBlueprintVersion;
    return this;
  }

   /**
   * Get expBlueprintVersion
   * @return expBlueprintVersion
  **/
  @ApiModelProperty(value = "")
  public String getExpBlueprintVersion() {
    return expBlueprintVersion;
  }

  public void setExpBlueprintVersion(String expBlueprintVersion) {
    this.expBlueprintVersion = expBlueprintVersion;
  }

  public ExpBlueprintInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ExpBlueprintInfo onBoardedNsdInfoId(List<String> onBoardedNsdInfoId) {
    this.onBoardedNsdInfoId = onBoardedNsdInfoId;
    return this;
  }

  public ExpBlueprintInfo addOnBoardedNsdInfoIdItem(String onBoardedNsdInfoIdItem) {
    if (this.onBoardedNsdInfoId == null) {
      this.onBoardedNsdInfoId = new ArrayList<String>();
    }
    this.onBoardedNsdInfoId.add(onBoardedNsdInfoIdItem);
    return this;
  }

   /**
   * Get onBoardedNsdInfoId
   * @return onBoardedNsdInfoId
  **/
  @ApiModelProperty(value = "")
  public List<String> getOnBoardedNsdInfoId() {
    return onBoardedNsdInfoId;
  }

  public void setOnBoardedNsdInfoId(List<String> onBoardedNsdInfoId) {
    this.onBoardedNsdInfoId = onBoardedNsdInfoId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExpBlueprintInfo expBlueprintInfo = (ExpBlueprintInfo) o;
    return Objects.equals(this.activeExpdId, expBlueprintInfo.activeExpdId) &&
        Objects.equals(this.expBlueprint, expBlueprintInfo.expBlueprint) &&
        Objects.equals(this.expBlueprintId, expBlueprintInfo.expBlueprintId) &&
        Objects.equals(this.expBlueprintVersion, expBlueprintInfo.expBlueprintVersion) &&
        Objects.equals(this.name, expBlueprintInfo.name) &&
        Objects.equals(this.onBoardedNsdInfoId, expBlueprintInfo.onBoardedNsdInfoId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeExpdId, expBlueprint, expBlueprintId, expBlueprintVersion, name, onBoardedNsdInfoId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExpBlueprintInfo {\n");
    
    sb.append("    activeExpdId: ").append(toIndentedString(activeExpdId)).append("\n");
    sb.append("    expBlueprint: ").append(toIndentedString(expBlueprint)).append("\n");
    sb.append("    expBlueprintId: ").append(toIndentedString(expBlueprintId)).append("\n");
    sb.append("    expBlueprintVersion: ").append(toIndentedString(expBlueprintVersion)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    onBoardedNsdInfoId: ").append(toIndentedString(onBoardedNsdInfoId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

