/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * Nsd
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class Nsd {
  @SerializedName("autoScalingRule")
  private List<NsAutoscalingRule> autoScalingRule = null;

  @SerializedName("designer")
  private String designer = null;

  @SerializedName("lifeCycleManagementScript")
  private List<LifeCycleManagementScript> lifeCycleManagementScript = null;

  @SerializedName("monitoredInfo")
  private List<MonitoredData> monitoredInfo = null;

  @SerializedName("nestedNsdId")
  private List<String> nestedNsdId = null;

  @SerializedName("nsDf")
  private List<NsDf> nsDf = null;

  @SerializedName("nsdIdentifier")
  private String nsdIdentifier = null;

  @SerializedName("nsdInvariantId")
  private String nsdInvariantId = null;

  @SerializedName("nsdName")
  private String nsdName = null;

  @SerializedName("pnfdId")
  private List<String> pnfdId = null;

  @SerializedName("sapd")
  private List<Sapd> sapd = null;

  @SerializedName("security")
  private SecurityParameters security = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("virtualLinkDesc")
  private List<NsVirtualLinkDesc> virtualLinkDesc = null;

  @SerializedName("vnfdId")
  private List<String> vnfdId = null;

  @SerializedName("vnffgd")
  private List<Vnffgd> vnffgd = null;

  public Nsd autoScalingRule(List<NsAutoscalingRule> autoScalingRule) {
    this.autoScalingRule = autoScalingRule;
    return this;
  }

  public Nsd addAutoScalingRuleItem(NsAutoscalingRule autoScalingRuleItem) {
    if (this.autoScalingRule == null) {
      this.autoScalingRule = new ArrayList<NsAutoscalingRule>();
    }
    this.autoScalingRule.add(autoScalingRuleItem);
    return this;
  }

   /**
   * Get autoScalingRule
   * @return autoScalingRule
  **/
  @ApiModelProperty(value = "")
  public List<NsAutoscalingRule> getAutoScalingRule() {
    return autoScalingRule;
  }

  public void setAutoScalingRule(List<NsAutoscalingRule> autoScalingRule) {
    this.autoScalingRule = autoScalingRule;
  }

  public Nsd designer(String designer) {
    this.designer = designer;
    return this;
  }

   /**
   * Get designer
   * @return designer
  **/
  @ApiModelProperty(value = "")
  public String getDesigner() {
    return designer;
  }

  public void setDesigner(String designer) {
    this.designer = designer;
  }

  public Nsd lifeCycleManagementScript(List<LifeCycleManagementScript> lifeCycleManagementScript) {
    this.lifeCycleManagementScript = lifeCycleManagementScript;
    return this;
  }

  public Nsd addLifeCycleManagementScriptItem(LifeCycleManagementScript lifeCycleManagementScriptItem) {
    if (this.lifeCycleManagementScript == null) {
      this.lifeCycleManagementScript = new ArrayList<LifeCycleManagementScript>();
    }
    this.lifeCycleManagementScript.add(lifeCycleManagementScriptItem);
    return this;
  }

   /**
   * Get lifeCycleManagementScript
   * @return lifeCycleManagementScript
  **/
  @ApiModelProperty(value = "")
  public List<LifeCycleManagementScript> getLifeCycleManagementScript() {
    return lifeCycleManagementScript;
  }

  public void setLifeCycleManagementScript(List<LifeCycleManagementScript> lifeCycleManagementScript) {
    this.lifeCycleManagementScript = lifeCycleManagementScript;
  }

  public Nsd monitoredInfo(List<MonitoredData> monitoredInfo) {
    this.monitoredInfo = monitoredInfo;
    return this;
  }

  public Nsd addMonitoredInfoItem(MonitoredData monitoredInfoItem) {
    if (this.monitoredInfo == null) {
      this.monitoredInfo = new ArrayList<MonitoredData>();
    }
    this.monitoredInfo.add(monitoredInfoItem);
    return this;
  }

   /**
   * Get monitoredInfo
   * @return monitoredInfo
  **/
  @ApiModelProperty(value = "")
  public List<MonitoredData> getMonitoredInfo() {
    return monitoredInfo;
  }

  public void setMonitoredInfo(List<MonitoredData> monitoredInfo) {
    this.monitoredInfo = monitoredInfo;
  }

  public Nsd nestedNsdId(List<String> nestedNsdId) {
    this.nestedNsdId = nestedNsdId;
    return this;
  }

  public Nsd addNestedNsdIdItem(String nestedNsdIdItem) {
    if (this.nestedNsdId == null) {
      this.nestedNsdId = new ArrayList<String>();
    }
    this.nestedNsdId.add(nestedNsdIdItem);
    return this;
  }

   /**
   * Get nestedNsdId
   * @return nestedNsdId
  **/
  @ApiModelProperty(value = "")
  public List<String> getNestedNsdId() {
    return nestedNsdId;
  }

  public void setNestedNsdId(List<String> nestedNsdId) {
    this.nestedNsdId = nestedNsdId;
  }

  public Nsd nsDf(List<NsDf> nsDf) {
    this.nsDf = nsDf;
    return this;
  }

  public Nsd addNsDfItem(NsDf nsDfItem) {
    if (this.nsDf == null) {
      this.nsDf = new ArrayList<NsDf>();
    }
    this.nsDf.add(nsDfItem);
    return this;
  }

   /**
   * Get nsDf
   * @return nsDf
  **/
  @ApiModelProperty(value = "")
  public List<NsDf> getNsDf() {
    return nsDf;
  }

  public void setNsDf(List<NsDf> nsDf) {
    this.nsDf = nsDf;
  }

  public Nsd nsdIdentifier(String nsdIdentifier) {
    this.nsdIdentifier = nsdIdentifier;
    return this;
  }

   /**
   * Get nsdIdentifier
   * @return nsdIdentifier
  **/
  @ApiModelProperty(value = "")
  public String getNsdIdentifier() {
    return nsdIdentifier;
  }

  public void setNsdIdentifier(String nsdIdentifier) {
    this.nsdIdentifier = nsdIdentifier;
  }

  public Nsd nsdInvariantId(String nsdInvariantId) {
    this.nsdInvariantId = nsdInvariantId;
    return this;
  }

   /**
   * Get nsdInvariantId
   * @return nsdInvariantId
  **/
  @ApiModelProperty(value = "")
  public String getNsdInvariantId() {
    return nsdInvariantId;
  }

  public void setNsdInvariantId(String nsdInvariantId) {
    this.nsdInvariantId = nsdInvariantId;
  }

  public Nsd nsdName(String nsdName) {
    this.nsdName = nsdName;
    return this;
  }

   /**
   * Get nsdName
   * @return nsdName
  **/
  @ApiModelProperty(value = "")
  public String getNsdName() {
    return nsdName;
  }

  public void setNsdName(String nsdName) {
    this.nsdName = nsdName;
  }

  public Nsd pnfdId(List<String> pnfdId) {
    this.pnfdId = pnfdId;
    return this;
  }

  public Nsd addPnfdIdItem(String pnfdIdItem) {
    if (this.pnfdId == null) {
      this.pnfdId = new ArrayList<String>();
    }
    this.pnfdId.add(pnfdIdItem);
    return this;
  }

   /**
   * Get pnfdId
   * @return pnfdId
  **/
  @ApiModelProperty(value = "")
  public List<String> getPnfdId() {
    return pnfdId;
  }

  public void setPnfdId(List<String> pnfdId) {
    this.pnfdId = pnfdId;
  }

  public Nsd sapd(List<Sapd> sapd) {
    this.sapd = sapd;
    return this;
  }

  public Nsd addSapdItem(Sapd sapdItem) {
    if (this.sapd == null) {
      this.sapd = new ArrayList<Sapd>();
    }
    this.sapd.add(sapdItem);
    return this;
  }

   /**
   * Get sapd
   * @return sapd
  **/
  @ApiModelProperty(value = "")
  public List<Sapd> getSapd() {
    return sapd;
  }

  public void setSapd(List<Sapd> sapd) {
    this.sapd = sapd;
  }

  public Nsd security(SecurityParameters security) {
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/
  @ApiModelProperty(value = "")
  public SecurityParameters getSecurity() {
    return security;
  }

  public void setSecurity(SecurityParameters security) {
    this.security = security;
  }

  public Nsd version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public Nsd virtualLinkDesc(List<NsVirtualLinkDesc> virtualLinkDesc) {
    this.virtualLinkDesc = virtualLinkDesc;
    return this;
  }

  public Nsd addVirtualLinkDescItem(NsVirtualLinkDesc virtualLinkDescItem) {
    if (this.virtualLinkDesc == null) {
      this.virtualLinkDesc = new ArrayList<NsVirtualLinkDesc>();
    }
    this.virtualLinkDesc.add(virtualLinkDescItem);
    return this;
  }

   /**
   * Get virtualLinkDesc
   * @return virtualLinkDesc
  **/
  @ApiModelProperty(value = "")
  public List<NsVirtualLinkDesc> getVirtualLinkDesc() {
    return virtualLinkDesc;
  }

  public void setVirtualLinkDesc(List<NsVirtualLinkDesc> virtualLinkDesc) {
    this.virtualLinkDesc = virtualLinkDesc;
  }

  public Nsd vnfdId(List<String> vnfdId) {
    this.vnfdId = vnfdId;
    return this;
  }

  public Nsd addVnfdIdItem(String vnfdIdItem) {
    if (this.vnfdId == null) {
      this.vnfdId = new ArrayList<String>();
    }
    this.vnfdId.add(vnfdIdItem);
    return this;
  }

   /**
   * Get vnfdId
   * @return vnfdId
  **/
  @ApiModelProperty(value = "")
  public List<String> getVnfdId() {
    return vnfdId;
  }

  public void setVnfdId(List<String> vnfdId) {
    this.vnfdId = vnfdId;
  }

  public Nsd vnffgd(List<Vnffgd> vnffgd) {
    this.vnffgd = vnffgd;
    return this;
  }

  public Nsd addVnffgdItem(Vnffgd vnffgdItem) {
    if (this.vnffgd == null) {
      this.vnffgd = new ArrayList<Vnffgd>();
    }
    this.vnffgd.add(vnffgdItem);
    return this;
  }

   /**
   * Get vnffgd
   * @return vnffgd
  **/
  @ApiModelProperty(value = "")
  public List<Vnffgd> getVnffgd() {
    return vnffgd;
  }

  public void setVnffgd(List<Vnffgd> vnffgd) {
    this.vnffgd = vnffgd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Nsd nsd = (Nsd) o;
    return Objects.equals(this.autoScalingRule, nsd.autoScalingRule) &&
        Objects.equals(this.designer, nsd.designer) &&
        Objects.equals(this.lifeCycleManagementScript, nsd.lifeCycleManagementScript) &&
        Objects.equals(this.monitoredInfo, nsd.monitoredInfo) &&
        Objects.equals(this.nestedNsdId, nsd.nestedNsdId) &&
        Objects.equals(this.nsDf, nsd.nsDf) &&
        Objects.equals(this.nsdIdentifier, nsd.nsdIdentifier) &&
        Objects.equals(this.nsdInvariantId, nsd.nsdInvariantId) &&
        Objects.equals(this.nsdName, nsd.nsdName) &&
        Objects.equals(this.pnfdId, nsd.pnfdId) &&
        Objects.equals(this.sapd, nsd.sapd) &&
        Objects.equals(this.security, nsd.security) &&
        Objects.equals(this.version, nsd.version) &&
        Objects.equals(this.virtualLinkDesc, nsd.virtualLinkDesc) &&
        Objects.equals(this.vnfdId, nsd.vnfdId) &&
        Objects.equals(this.vnffgd, nsd.vnffgd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(autoScalingRule, designer, lifeCycleManagementScript, monitoredInfo, nestedNsdId, nsDf, nsdIdentifier, nsdInvariantId, nsdName, pnfdId, sapd, security, version, virtualLinkDesc, vnfdId, vnffgd);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Nsd {\n");
    
    sb.append("    autoScalingRule: ").append(toIndentedString(autoScalingRule)).append("\n");
    sb.append("    designer: ").append(toIndentedString(designer)).append("\n");
    sb.append("    lifeCycleManagementScript: ").append(toIndentedString(lifeCycleManagementScript)).append("\n");
    sb.append("    monitoredInfo: ").append(toIndentedString(monitoredInfo)).append("\n");
    sb.append("    nestedNsdId: ").append(toIndentedString(nestedNsdId)).append("\n");
    sb.append("    nsDf: ").append(toIndentedString(nsDf)).append("\n");
    sb.append("    nsdIdentifier: ").append(toIndentedString(nsdIdentifier)).append("\n");
    sb.append("    nsdInvariantId: ").append(toIndentedString(nsdInvariantId)).append("\n");
    sb.append("    nsdName: ").append(toIndentedString(nsdName)).append("\n");
    sb.append("    pnfdId: ").append(toIndentedString(pnfdId)).append("\n");
    sb.append("    sapd: ").append(toIndentedString(sapd)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    virtualLinkDesc: ").append(toIndentedString(virtualLinkDesc)).append("\n");
    sb.append("    vnfdId: ").append(toIndentedString(vnfdId)).append("\n");
    sb.append("    vnffgd: ").append(toIndentedString(vnffgd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

