/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * NsToLevelMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class NsToLevelMapping {
  @SerializedName("nsProfileId")
  private String nsProfileId = null;

  @SerializedName("numberOfInstances")
  private Integer numberOfInstances = null;

  public NsToLevelMapping nsProfileId(String nsProfileId) {
    this.nsProfileId = nsProfileId;
    return this;
  }

   /**
   * Get nsProfileId
   * @return nsProfileId
  **/
  @ApiModelProperty(value = "")
  public String getNsProfileId() {
    return nsProfileId;
  }

  public void setNsProfileId(String nsProfileId) {
    this.nsProfileId = nsProfileId;
  }

  public NsToLevelMapping numberOfInstances(Integer numberOfInstances) {
    this.numberOfInstances = numberOfInstances;
    return this;
  }

   /**
   * Get numberOfInstances
   * @return numberOfInstances
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfInstances() {
    return numberOfInstances;
  }

  public void setNumberOfInstances(Integer numberOfInstances) {
    this.numberOfInstances = numberOfInstances;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NsToLevelMapping nsToLevelMapping = (NsToLevelMapping) o;
    return Objects.equals(this.nsProfileId, nsToLevelMapping.nsProfileId) &&
        Objects.equals(this.numberOfInstances, nsToLevelMapping.numberOfInstances);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsProfileId, numberOfInstances);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NsToLevelMapping {\n");
    
    sb.append("    nsProfileId: ").append(toIndentedString(nsProfileId)).append("\n");
    sb.append("    numberOfInstances: ").append(toIndentedString(numberOfInstances)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

