/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * OnboardExpBlueprintRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class OnboardExpBlueprintRequest {
  @SerializedName("expBlueprint")
  private ExpBlueprint expBlueprint = null;

  @SerializedName("nsds")
  private List<Nsd> nsds = null;

  @SerializedName("translationRules")
  private List<VsdNsdTranslationRule> translationRules = null;

  public OnboardExpBlueprintRequest expBlueprint(ExpBlueprint expBlueprint) {
    this.expBlueprint = expBlueprint;
    return this;
  }

   /**
   * Get expBlueprint
   * @return expBlueprint
  **/
  @ApiModelProperty(value = "")
  public ExpBlueprint getExpBlueprint() {
    return expBlueprint;
  }

  public void setExpBlueprint(ExpBlueprint expBlueprint) {
    this.expBlueprint = expBlueprint;
  }

  public OnboardExpBlueprintRequest nsds(List<Nsd> nsds) {
    this.nsds = nsds;
    return this;
  }

  public OnboardExpBlueprintRequest addNsdsItem(Nsd nsdsItem) {
    if (this.nsds == null) {
      this.nsds = new ArrayList<Nsd>();
    }
    this.nsds.add(nsdsItem);
    return this;
  }

   /**
   * Get nsds
   * @return nsds
  **/
  @ApiModelProperty(value = "")
  public List<Nsd> getNsds() {
    return nsds;
  }

  public void setNsds(List<Nsd> nsds) {
    this.nsds = nsds;
  }

  public OnboardExpBlueprintRequest translationRules(List<VsdNsdTranslationRule> translationRules) {
    this.translationRules = translationRules;
    return this;
  }

  public OnboardExpBlueprintRequest addTranslationRulesItem(VsdNsdTranslationRule translationRulesItem) {
    if (this.translationRules == null) {
      this.translationRules = new ArrayList<VsdNsdTranslationRule>();
    }
    this.translationRules.add(translationRulesItem);
    return this;
  }

   /**
   * Get translationRules
   * @return translationRules
  **/
  @ApiModelProperty(value = "")
  public List<VsdNsdTranslationRule> getTranslationRules() {
    return translationRules;
  }

  public void setTranslationRules(List<VsdNsdTranslationRule> translationRules) {
    this.translationRules = translationRules;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnboardExpBlueprintRequest onboardExpBlueprintRequest = (OnboardExpBlueprintRequest) o;
    return Objects.equals(this.expBlueprint, onboardExpBlueprintRequest.expBlueprint) &&
        Objects.equals(this.nsds, onboardExpBlueprintRequest.nsds) &&
        Objects.equals(this.translationRules, onboardExpBlueprintRequest.translationRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expBlueprint, nsds, translationRules);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnboardExpBlueprintRequest {\n");
    
    sb.append("    expBlueprint: ").append(toIndentedString(expBlueprint)).append("\n");
    sb.append("    nsds: ").append(toIndentedString(nsds)).append("\n");
    sb.append("    translationRules: ").append(toIndentedString(translationRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

