/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * ScaleNsToLevelData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class ScaleNsToLevelData {
  @SerializedName("nsInstantiationLevel")
  private String nsInstantiationLevel = null;

  @SerializedName("nsScaleInfo")
  private List<NsScaleInfo> nsScaleInfo = null;

  public ScaleNsToLevelData nsInstantiationLevel(String nsInstantiationLevel) {
    this.nsInstantiationLevel = nsInstantiationLevel;
    return this;
  }

   /**
   * Get nsInstantiationLevel
   * @return nsInstantiationLevel
  **/
  @ApiModelProperty(value = "")
  public String getNsInstantiationLevel() {
    return nsInstantiationLevel;
  }

  public void setNsInstantiationLevel(String nsInstantiationLevel) {
    this.nsInstantiationLevel = nsInstantiationLevel;
  }

  public ScaleNsToLevelData nsScaleInfo(List<NsScaleInfo> nsScaleInfo) {
    this.nsScaleInfo = nsScaleInfo;
    return this;
  }

  public ScaleNsToLevelData addNsScaleInfoItem(NsScaleInfo nsScaleInfoItem) {
    if (this.nsScaleInfo == null) {
      this.nsScaleInfo = new ArrayList<NsScaleInfo>();
    }
    this.nsScaleInfo.add(nsScaleInfoItem);
    return this;
  }

   /**
   * Get nsScaleInfo
   * @return nsScaleInfo
  **/
  @ApiModelProperty(value = "")
  public List<NsScaleInfo> getNsScaleInfo() {
    return nsScaleInfo;
  }

  public void setNsScaleInfo(List<NsScaleInfo> nsScaleInfo) {
    this.nsScaleInfo = nsScaleInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScaleNsToLevelData scaleNsToLevelData = (ScaleNsToLevelData) o;
    return Objects.equals(this.nsInstantiationLevel, scaleNsToLevelData.nsInstantiationLevel) &&
        Objects.equals(this.nsScaleInfo, scaleNsToLevelData.nsScaleInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nsInstantiationLevel, nsScaleInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScaleNsToLevelData {\n");
    
    sb.append("    nsInstantiationLevel: ").append(toIndentedString(nsInstantiationLevel)).append("\n");
    sb.append("    nsScaleInfo: ").append(toIndentedString(nsScaleInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

