/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * VnfToLevelMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-10-26T20:09:54.213Z")



public class VnfToLevelMapping {
  @SerializedName("numberOfInstances")
  private Integer numberOfInstances = null;

  @SerializedName("vnfProfileId")
  private String vnfProfileId = null;

  public VnfToLevelMapping numberOfInstances(Integer numberOfInstances) {
    this.numberOfInstances = numberOfInstances;
    return this;
  }

   /**
   * Get numberOfInstances
   * @return numberOfInstances
  **/
  @ApiModelProperty(value = "")
  public Integer getNumberOfInstances() {
    return numberOfInstances;
  }

  public void setNumberOfInstances(Integer numberOfInstances) {
    this.numberOfInstances = numberOfInstances;
  }

  public VnfToLevelMapping vnfProfileId(String vnfProfileId) {
    this.vnfProfileId = vnfProfileId;
    return this;
  }

   /**
   * Get vnfProfileId
   * @return vnfProfileId
  **/
  @ApiModelProperty(value = "")
  public String getVnfProfileId() {
    return vnfProfileId;
  }

  public void setVnfProfileId(String vnfProfileId) {
    this.vnfProfileId = vnfProfileId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VnfToLevelMapping vnfToLevelMapping = (VnfToLevelMapping) o;
    return Objects.equals(this.numberOfInstances, vnfToLevelMapping.numberOfInstances) &&
        Objects.equals(this.vnfProfileId, vnfToLevelMapping.vnfProfileId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfInstances, vnfProfileId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VnfToLevelMapping {\n");
    
    sb.append("    numberOfInstances: ").append(toIndentedString(numberOfInstances)).append("\n");
    sb.append("    vnfProfileId: ").append(toIndentedString(vnfProfileId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

