/*
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.eveportal.client.api;

import io.swagger.eveportal.client.ApiCallback;
import io.swagger.eveportal.client.ApiClient;
import io.swagger.eveportal.client.ApiException;
import io.swagger.eveportal.client.ApiResponse;
import io.swagger.eveportal.client.Configuration;
import io.swagger.eveportal.client.Pair;
import io.swagger.eveportal.client.ProgressRequestBody;
import io.swagger.eveportal.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.swagger.eveportal.client.model.TestCaseDescriptor;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TestCaseDescriptorCatalogueApiApi {
    private ApiClient apiClient;

    public TestCaseDescriptorCatalogueApiApi() {
        this(Configuration.getDefaultApiClient());
    }

    public TestCaseDescriptorCatalogueApiApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for getAllTestCaseDescriptorsUsingGET
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getAllTestCaseDescriptorsUsingGETCall(Boolean authenticated, String authorities0Authority, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/portal/catalogue/testcasedescriptor";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (authenticated != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("authenticated", authenticated));
        if (authorities0Authority != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("authorities[0].authority", authorities0Authority));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getAllTestCaseDescriptorsUsingGETValidateBeforeCall(Boolean authenticated, String authorities0Authority, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        

        com.squareup.okhttp.Call call = getAllTestCaseDescriptorsUsingGETCall(authenticated, authorities0Authority, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Query ALL the Test Case Descriptors
     * 
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @return List&lt;TestCaseDescriptor&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public List<TestCaseDescriptor> getAllTestCaseDescriptorsUsingGET(Boolean authenticated, String authorities0Authority) throws ApiException {
        ApiResponse<List<TestCaseDescriptor>> resp = getAllTestCaseDescriptorsUsingGETWithHttpInfo(authenticated, authorities0Authority);
        return resp.getData();
    }

    /**
     * Query ALL the Test Case Descriptors
     * 
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @return ApiResponse&lt;List&lt;TestCaseDescriptor&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<List<TestCaseDescriptor>> getAllTestCaseDescriptorsUsingGETWithHttpInfo(Boolean authenticated, String authorities0Authority) throws ApiException {
        com.squareup.okhttp.Call call = getAllTestCaseDescriptorsUsingGETValidateBeforeCall(authenticated, authorities0Authority, null, null);
        Type localVarReturnType = new TypeToken<List<TestCaseDescriptor>>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Query ALL the Test Case Descriptors (asynchronously)
     * 
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getAllTestCaseDescriptorsUsingGETAsync(Boolean authenticated, String authorities0Authority, final ApiCallback<List<TestCaseDescriptor>> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getAllTestCaseDescriptorsUsingGETValidateBeforeCall(authenticated, authorities0Authority, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<List<TestCaseDescriptor>>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
    /**
     * Build call for getTcDescriptorUsingGET
     * @param tcdId tcdId (required)
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call getTcDescriptorUsingGETCall(String tcdId, Boolean authenticated, String authorities0Authority, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/portal/catalogue/testcasedescriptor/{tcdId}"
            .replaceAll("\\{" + "tcdId" + "\\}", apiClient.escapeString(tcdId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        if (authenticated != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("authenticated", authenticated));
        if (authorities0Authority != null)
        localVarQueryParams.addAll(apiClient.parameterToPair("authorities[0].authority", authorities0Authority));

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "*/*"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call getTcDescriptorUsingGETValidateBeforeCall(String tcdId, Boolean authenticated, String authorities0Authority, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'tcdId' is set
        if (tcdId == null) {
            throw new ApiException("Missing the required parameter 'tcdId' when calling getTcDescriptorUsingGET(Async)");
        }
        

        com.squareup.okhttp.Call call = getTcDescriptorUsingGETCall(tcdId, authenticated, authorities0Authority, progressListener, progressRequestListener);
        return call;

    }

    /**
     * Query a Test Case Descriptor with a given ID
     * 
     * @param tcdId tcdId (required)
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @return TestCaseDescriptor
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public TestCaseDescriptor getTcDescriptorUsingGET(String tcdId, Boolean authenticated, String authorities0Authority) throws ApiException {
        ApiResponse<TestCaseDescriptor> resp = getTcDescriptorUsingGETWithHttpInfo(tcdId, authenticated, authorities0Authority);
        return resp.getData();
    }

    /**
     * Query a Test Case Descriptor with a given ID
     * 
     * @param tcdId tcdId (required)
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @return ApiResponse&lt;TestCaseDescriptor&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<TestCaseDescriptor> getTcDescriptorUsingGETWithHttpInfo(String tcdId, Boolean authenticated, String authorities0Authority) throws ApiException {
        com.squareup.okhttp.Call call = getTcDescriptorUsingGETValidateBeforeCall(tcdId, authenticated, authorities0Authority, null, null);
        Type localVarReturnType = new TypeToken<TestCaseDescriptor>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * Query a Test Case Descriptor with a given ID (asynchronously)
     * 
     * @param tcdId tcdId (required)
     * @param authenticated  (optional)
     * @param authorities0Authority  (optional)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call getTcDescriptorUsingGETAsync(String tcdId, Boolean authenticated, String authorities0Authority, final ApiCallback<TestCaseDescriptor> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = getTcDescriptorUsingGETValidateBeforeCall(tcdId, authenticated, authorities0Authority, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<TestCaseDescriptor>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
